---
rdoc_url: https://bogomips.org/clogger/
cgit_url: https://bogomips.org/clogger.git
git_url: git://bogomips.org/clogger.git
public_email: clogger-public@bogomips.org
private_email: clogger@bogomips.org
ml_url:
- https://bogomips.org/clogger-public/
- http://ou63pmih66umazou.onion/clogger-public/
- nntp://news.public-inbox.org/inbox.comp.lang.ruby.clogger
source_code:
- git clone git://bogomips.org/clogger.git
- git clone https://bogomips.org/clogger.git
